robotblack_drive:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  # Valocity Controllers ---------------------------------------
  joint1_right_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: right_joint_wheel
    pid: {p: 2.0, i: 0.0, d: 0.0}
  # Valocity Controllers ---------------------------------------
  joint2_left_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: left_joint_wheel
    pid: {p: 2.0, i: 0.0, d: 0.0}
